#!/usr/bin/env python3
"""Raise the Pokémon-ness of low-scoring answers by asking Claude to revise them.

    python3 scripts/revise.py --lowest 5 --dry-run     # see what it would do
    python3 scripts/revise.py --lowest 5               # revise, keep only improvements
    python3 scripts/revise.py --id 082                 # revise one answer
    python3 scripts/revise.py --lowest 3 --min-gain 5  # require +5 to keep

The prompt lives in `prompts/revise-pokemon-answer.md` so that changes to the
revision instructions show up as a reviewable diff rather than buried in code.

Provenance note: the revisions committed to this repository before this script
existed were written by hand, not generated by it. Its purpose is to make future
rounds reproducible — same prompt, same model, same accept/reject rule, recorded
in git — rather than to reconstruct past ones.

Guardrails, because the score is a proxy and proxies get gamed:
  * a revision is discarded unless it scores higher than the original;
  * `scripts/validate.py` must still pass on the result;
  * front matter must come back byte-identical;
  * `--dry-run` writes nothing and costs one API call per answer.

Credentials: the SDK resolves ANTHROPIC_API_KEY, ANTHROPIC_AUTH_TOKEN, or an
`ant auth login` profile. No key is read or stored by this script.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

from build_dataset import read_catalogue  # noqa: E402
from pokemon_score import body_of, score_text  # noqa: E402

MODEL = "claude-opus-5"
PROMPT_PATH = ROOT / "prompts" / "revise-pokemon-answer.md"


def load_prompt() -> tuple[str, str]:
    """Split the prompt file into (system, user template)."""
    text = PROMPT_PATH.read_text(encoding="utf-8")
    _, rest = text.split("---SYSTEM---", 1)
    system, user = rest.split("---USER---", 1)
    return system.strip(), user.strip()


def front_matter(text: str) -> str:
    parts = text.split("---\n")
    return "---\n".join(parts[:2]) + "---\n" if len(parts) > 2 else ""


def render(template: str, **fields: str) -> str:
    for key, value in fields.items():
        template = template.replace("{{" + key + "}}", value)
    return template


def revise_one(client, entry: dict, dry_run: bool, min_gain: float) -> dict:
    qid, slug = entry["id"], entry["slug"]
    pk_path = ROOT / "answers" / "pokemon" / f"{qid}-{slug}.md"
    sr_path = ROOT / "answers" / "serious" / f"{qid}-{slug}.md"

    original = pk_path.read_text(encoding="utf-8")
    before = score_text(body_of(pk_path))
    used = ", ".join(sorted(h.split("×")[0] for hits in before["hits"].values() for h in hits))

    system, user_template = load_prompt()
    user = render(
        user_template,
        SLUG=f"{qid} — {slug}",
        QUESTION=entry["question"],
        SCORE=f"{before['score']:.1f}",
        DISTINCT=str(before["distinct"]),
        HITS=used or "(none)",
        SERIOUS=sr_path.read_text(encoding="utf-8"),
        POKEMON=original,
    )

    print(f"\n=== {qid} {slug} — {before['score']:.1f}/100 ===")
    if dry_run:
        print(f"    [dry run] prompt {len(system) + len(user):,} chars; no call made")
        return {"id": qid, "status": "dry-run", "before": before["score"]}

    # Streaming because the revision is a whole file; adaptive thinking because
    # the model has to hold the serious answer, the Pokémon answer and the
    # accuracy constraints together. Server-side fallbacks are on by default so a
    # policy decline retries on another model inside the same call.
    with client.beta.messages.stream(
        model=MODEL,
        max_tokens=64000,
        thinking={"type": "adaptive"},
        betas=["server-side-fallback-2026-07-01"],
        fallbacks="default",
        system=system,
        messages=[{"role": "user", "content": user}],
    ) as stream:
        message = stream.get_final_message()

    if message.stop_reason == "refusal":
        detail = getattr(message, "stop_details", None)
        print(f"    ✗ declined ({getattr(detail, 'category', 'unknown')}) — left unchanged")
        return {"id": qid, "status": "refused", "before": before["score"]}

    revised = "".join(b.text for b in message.content if b.type == "text").strip() + "\n"
    revised = re.sub(r"\A```(?:markdown)?\n(.*)\n```\s*\Z", r"\1\n", revised, flags=re.S)

    if front_matter(revised) != front_matter(original):
        print("    ✗ front matter changed — rejected")
        return {"id": qid, "status": "bad-front-matter", "before": before["score"]}

    backup = pathlib.Path(tempfile.mkdtemp()) / pk_path.name
    shutil.copy(pk_path, backup)
    pk_path.write_text(revised, encoding="utf-8")

    after = score_text(body_of(pk_path))
    gain = after["score"] - before["score"]
    checks = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "validate.py")],
        capture_output=True, text=True,
    )

    if checks.returncode != 0:
        shutil.copy(backup, pk_path)
        print("    ✗ validate.py failed — reverted")
        return {"id": qid, "status": "invalid", "before": before["score"]}
    if gain < min_gain:
        shutil.copy(backup, pk_path)
        print(f"    ✗ {after['score']:.1f} (gain {gain:+.1f} < {min_gain}) — reverted")
        return {"id": qid, "status": "no-gain", "before": before["score"], "after": after["score"]}

    print(f"    ✓ {before['score']:.1f} → {after['score']:.1f}  ({gain:+.1f}), "
          f"{before['distinct']} → {after['distinct']} distinct entities")
    return {"id": qid, "status": "revised", "before": before["score"], "after": after["score"]}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    group = ap.add_mutually_exclusive_group(required=True)
    group.add_argument("--lowest", type=int, metavar="N", help="revise the N lowest-scoring answers")
    group.add_argument("--id", action="append", metavar="ID", help="revise a specific question id")
    ap.add_argument("--dry-run", action="store_true", help="build prompts, make no API calls")
    ap.add_argument("--min-gain", type=float, default=1.0,
                    help="minimum score gain to keep a revision (default 1.0)")
    args = ap.parse_args()

    catalogue = {e["id"]: e for e in read_catalogue()}
    if args.id:
        missing = [i for i in args.id if i not in catalogue]
        if missing:
            ap.error(f"unknown question id(s): {', '.join(missing)}")
        targets = [catalogue[i] for i in args.id]
    else:
        scored = sorted(
            catalogue.values(),
            key=lambda e: score_text(body_of(
                ROOT / "answers" / "pokemon" / f"{e['id']}-{e['slug']}.md"))["score"],
        )
        targets = scored[: args.lowest]

    client = None
    if not args.dry_run:
        try:
            import anthropic
        except ImportError:
            print("anthropic SDK not installed:  pip install anthropic", file=sys.stderr)
            return 1
        try:
            client = anthropic.Anthropic()
        except Exception as exc:
            print(f"could not construct a client: {exc}\n"
                  "Set ANTHROPIC_API_KEY, or run `ant auth login`.", file=sys.stderr)
            return 1

    results = [revise_one(client, e, args.dry_run, args.min_gain) for e in targets]

    kept = [r for r in results if r["status"] == "revised"]
    print(f"\n{len(kept)}/{len(results)} revisions kept")
    if kept:
        print(f"mean gain on kept: "
              f"{sum(r['after'] - r['before'] for r in kept) / len(kept):+.1f}")
        print("\nRegenerate the ledger and commit:")
        print("  python3 scripts/pokemon_score.py && python3 scripts/build_dataset.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
